# Build options
SKETCHES :=        CentralTinyBoy TinyDisplay TinyInput TinyProgSD
BOARD :=           attiny:avr:ATtinyX5:cpu=attiny85,clock=internal8
BOARD_NAME =       $(subst :,.,$(BOARD))
PORT :=            /dev/ttyACM0
ASC :=             arduino

# Autogenerated project settings
define make-project-target
.PHONY : $1
$1 : $1/$1.ino
	$(ASC) --verify --board $(BOARD) $1/$1.ino

$1-upload : $1/$1.ino
	$(ASC) --upload --board $(BOARD) --port $(PORT) $1/$1.ino
endef

# Targets
ALL_BUILDS :=      $(foreach sketch,$(SKETCHES),$(sketch))
.PHONY : all
all : $(ALL_BUILDS)
	

$(foreach sketch,$(SKETCHES), $(eval $(call make-project-target,$(sketch))))

.PHONY : clean
clean :
	rm -rf */build

.PHONY : list
list :
	@$(MAKE) -pRrq -f $(lastword $(MAKEFILE_LIST)) : 2>/dev/null | awk -v RS= -F: '/^# File/,/^# Finished Make data base/ {if ($$1 !~ "^[#.]") {print $$1}}' | sort | egrep -v -e '^[^[:alnum:]]' -e '^$@$$'
