# Build options
SKETCHES :=        CentralTinyBoy TinyDisplay TinyFram TinyInput TinyProgSD
BOARD :=           attiny:avr:ATtinyX5
BOARD_NAME =       $(subst :,.,$(BOARD))
PORT :=            /dev/ttyACM0
ASC :=             arduino-cli

# Autogenerated project settings
define make-project-target
$1/build/$(BOARD_NAME)/$1.ino.hex : $1/$1.ino $(wildcard $1/*.hpp)
	$(ASC) compile -b $(BOARD) $1
	
$1-upload : $1/build/$(BOARD_NAME)/$1.ino.hex
	$(ASC) upload -b $(BOARD) -p $(PORT) $1
endef

# Targets
ALL_BUILDS :=      $(foreach sketch,$(SKETCHES),$(sketch)/build/$(BOARD_NAME)/$(sketch).ino.hex)
.PHONY : all
all : $(ALL_BUILDS)
	

$(foreach sketch,$(SKETCHES), $(eval $(call make-project-target,$(sketch))))

.PHONY : clean
clean :
	rm -rf */build

.PHONY : list
list :
	@$(MAKE) -pRrq -f $(lastword $(MAKEFILE_LIST)) : 2>/dev/null | awk -v RS= -F: '/^# File/,/^# Finished Make data base/ {if ($$1 !~ "^[#.]") {print $$1}}' | sort | egrep -v -e '^[^[:alnum:]]' -e '^$@$$'
